# Name : Yash Manharbhai Patel
# Student ID : A20451170
# Course : CS512 - Computer Vision
# Semester : Fall20
# Homework-0

In [61]:
import numpy as np

# Question A

In [62]:
A_a = np.array([[1],[2],[3]])
B_a = np.array([[4],[5],[6]])
C_a = np.array([[-1],[1],[3]])

# 1. 2A-B

In [63]:
ans_a1 = np.multiply(2,A_a)
ans_a1 = np.subtract(ans_a1,B_a)
print(ans_a1)

[[-2]
 [-1]
 [ 0]]


# 2. ||A|| and the angle of A relative to the positive X axis

In [64]:
ans_a21 = np.linalg.norm(A_a, ord=2)
print(ans_a21)

x_axis = np.array([[1],[0],[0]])
cos_theta_x = np.dot(x_axis.reshape((3)), A_a.reshape((3)))
cos_theta_x = cos_theta_x / (ans_a21 * np.linalg.norm(x_axis, ord=2))
theta_x = np.arccos(cos_theta_x)
ans_a22 = 180 * theta_x / np.pi
print(ans_a22)

3.7416573867739413
74.498640433063


# 3. A, a unit vector in the direction of A

In [65]:
ans_a3 = np.divide(A_a, ans_a21)
print(ans_a3)

[[0.26726124]
 [0.53452248]
 [0.80178373]]


# 4. the direction cosines of A

In [66]:
x_axis = np.array([[1],[0],[0]])
y_axis = np.array([[0],[1],[0]])
z_axis = np.array([[0],[0],[1]])

cos_theta_x = np.dot(x_axis.reshape((3)), A_a.reshape((3))) / (ans_a21 * np.linalg.norm(x_axis, ord=2))
cos_theta_y = np.dot(y_axis.reshape((3)), A_a.reshape((3))) / (ans_a21 * np.linalg.norm(y_axis, ord=2))
cos_theta_z = np.dot(z_axis.reshape((3)), A_a.reshape((3))) / (ans_a21 * np.linalg.norm(z_axis, ord=2))

print(cos_theta_x)
print(cos_theta_y)
print(cos_theta_z)

0.2672612419124244
0.5345224838248488
0.8017837257372732


# 5. A dot B and B dot A

In [67]:
ans_a51 = np.dot(A_a.reshape((3)), B_a.reshape((3)))
print(ans_a51)
ans_a52 = np.dot(B_a.reshape((3)), A_a.reshape((3)))
print(ans_a52)

32
32


# 6. the angle between A and B

In [68]:
cos_theta_ab = ans_a51 / (ans_a21 * np.linalg.norm(B_a, ord=2))
theta_ab = np.arccos(cos_theta_ab)
ans_a6 = 180 * theta_ab / np.pi
print(ans_a6)

12.933154491899078


# 7. a vector which is perpendicular to A

We can find a vector which is perpendicular by taking cross product of A and any arbitrary vector.

Because cross product of any two vector gives a vector which is perpendicular to a plan creat by two vectors.

Suppose any arbitrary vector is [1, 0, 0].

dot product of any two perpendicular vectors is zero.

In [69]:
arbi_vector = np.array([[1], [0], [0]])
ans_a7 = np.cross(A_a.T, arbi_vector.T).T
print(ans_a7)
print(np.dot(ans_a7.reshape(3), A_a.reshape(3)))

[[ 0]
 [ 3]
 [-2]]
0


# 8. A x B and B x A

In [70]:
ans_a81 = np.cross(A_a.T, B_a.T).T
print(ans_a81)
ans_a82 = np.cross(B_a.T, A_a.T).T
print(ans_a82)

[[-3]
 [ 6]
 [-3]]
[[ 3]
 [-6]
 [ 3]]


# 9. a vector which is perpendicular to both A and B

In [71]:
ans_a9 = np.cross(A_a.T, B_a.T).T
print(ans_a9)

[[-3]
 [ 6]
 [-3]]


# 10. the linear dependency between A, B, C

In [72]:
stack = np.column_stack([B_a, C_a])
coefficient = np.linalg.lstsq(stack, A_a)
print(coefficient[0])

[[0.33333333]
 [0.33333333]]


C:\Users\yashm\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


A = 0.33333333B + 0.33333333C

3A = B + C

# 11. A.T B and A B.T

In [73]:
ans_a111 = np.matmul(A_a.T, B_a)
print(ans_a111)
ans_a112 = np.matmul(A_a, B_a.T)
print(ans_a112)

[[32]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# Question B

In [74]:
A_b = np.array([[1,2,3],[4,-2,3],[0,5,-1]])
B_b = np.array([[1,2,1],[2,1,-4],[3,-2,1]])
C_b = np.array([[1,2,3],[4,5,6],[-1,1,3]])

# 1. 2A-B

In [75]:
ans_b1 = np.multiply(2,A_b)
ans_b1 = np.subtract(ans_b1,B_b)
print(ans_b1)

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


# 2. AB and BA

In [76]:
ans_b21 = np.matmul(A_b, B_b)
print(ans_b21)
ans_b22 = np.matmul(B_b, A_b)
print(ans_b22)

[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


# 3. (AB).T and B.T A.T

In [77]:
ans_b31 = ans_b21.T
print(ans_b31)
ans_b32 = np.matmul(B_b.T, A_b.T)
print(ans_b32)

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


# 4. |A| and |C|

In [78]:
ans_b41 = np.linalg.det(A_b)
print(ans_b41)
ans_b42 = np.linalg.det(C_b)
print(ans_b42)

54.999999999999964
0.0


# 5. the matrix (A, B, or C) in which the row vectors form an orthogonal set

In [79]:
dot_a1a2 = np.dot(A_b[0, :], A_b[1, :])
print(dot_a1a2)
dot_a2a3 = np.dot(A_b[1, :], A_b[2, :])
print(dot_a2a3)
dot_a1a3 = np.dot(A_b[0, :], A_b[2, :])
print(dot_a1a3)

dot_b1b2 = np.dot(B_b[0, :], B_b[1, :])
print(dot_b1b2)
dot_b2b3 = np.dot(B_b[1, :], B_b[2, :])
print(dot_b2b3)
dot_b1b3 = np.dot(B_b[0, :], B_b[2, :])
print(dot_b1b3)

dot_c1c2 = np.dot(C_b[0, :], C_b[1, :])
print(dot_c1c2)
dot_c2c3 = np.dot(C_b[1, :], C_b[2, :])
print(dot_c2c3)
dot_c1c3 = np.dot(C_b[0, :], C_b[2, :])
print(dot_c1c3)

9
-13
7
0
0
0
32
19
10


# 6. A inverse and B inverse

In [80]:
ans_b61 = np.linalg.inv(A_b)
print(ans_b61)
ans_b62 = np.linalg.inv(B_b)
print(ans_b62)

[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


# Question C

In [81]:
A_c = np.array([[1, 2], [3, 2]])
B_c = np.array([[2, -2], [-2, 5]])

# 1. the eigenvalues and corrosponding eigenvectors of A

In [82]:
eigenvalues, eigenvectors = np.linalg.eig(A_c)
ans_c11 = eigenvalues
ans_c12 = eigenvectors
print(ans_c11)
print(ans_c12)

[-1.  4.]
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


# 2. the matrix VinverseAV where V is composed of the the eigenvectors of A

In [83]:
V = eigenvectors
V_inv = np.linalg.inv(V)
ans_c2 = np.matmul(np.matmul(V_inv, A_c), V)
print(ans_c2)

[[-1.00000000e+00 -7.21644966e-16]
 [ 0.00000000e+00  4.00000000e+00]]


# 3. the dot product between the eigenvectors of A

In [84]:
ans_c3 = np.dot(eigenvectors[:, 0], eigenvectors[:, 1])
print(ans_c3)

-0.19611613513818388


# 4. the dot product between the eigenvectors of B

In [85]:
eigenvalues, eigenvectors = np.linalg.eig(B_c)
print(eigenvalues)
print(eigenvectors)
ans_c4 = np.dot(eigenvectors[:, 0], eigenvectors[:, 1])
print(ans_c4)

[1. 6.]
[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]
0.0


# 5. the property of the eigenvectors of B

Here, B is a symmetric matrix.

B = B.T

=> First property, all eigenvalues of B are real.

   {1, 6} belongs to Real Number Set
   
=> Second property, the eigenvectors of B are orthonormal i.e. the composed matrix of eigenvectors is an orthogonal matrix.

In [86]:
eigenvectors[:, 0] = eigenvectors[:, 0] / np.linalg.norm(eigenvectors[:, 0], ord=2)
eigenvectors[:, 1] = eigenvectors[:, 1] / np.linalg.norm(eigenvectors[:, 1], ord=2)
print(eigenvectors)
ans_c521 = np.dot(eigenvectors[:, 0], eigenvectors[:, 1])
print(ans521)

[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]
0.0


this eigenvectors are orthonormal.

In [87]:
ans522 = np.linalg.norm(eigenvectors[:, 0], ord=2)
ans523 = np.linalg.norm(eigenvectors[:, 0], ord=2)
print(ans522)
print(ans523)

1.0
1.0


this is orthogonal

eigenvectors eigenvectors.T = eigenvectors.T eigenvectors = I

eigenvectors = Inv(eigenvectors)

In [88]:
ans524 = np.matmul(eigenvectors.T, eigenvectors)
ans525 = np.matmul(eigenvectors, eigenvectors.T)
print(ans524)
print(ans525)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [89]:
ans526 = np.linalg.inv(eigenvectors)
print(eigenvectors.T)
print(ans526)

[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
